name: CI Tests
on: [push]
env:
  cache-version: v2
jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 3
    strategy: 
      matrix: 
        node-version: [16, 18, 19, 20]
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache npm
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ env.cache-version }}-${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles(format('{0}{1}', github.workspace, '/package-lock.json')) }}
        restore-keys: |
          ${{ env.cache-version }}-${{ runner.os }}-node-${{ matrix.node-version }}-
    - name: npm ci, build, and test
      run: |
        npm ci
        npm run build
        npm run test
